spring:
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always

jwt:
  secret: cdfbsdvfbfgnsdxfcbdcgnbfszxfdcsd389defhnbedsfvbgedthjnedfbhedrjntrdfghrdb7345235463254457645766756edfhesdrdfthgedsrhdsfvegtfnhbedrfhbg9

logging:
  level:
    com:
      max:
        stock_feed_api: trace

mybatis:
  configuration:
    map-underscore-to-camel-case: true
